FROM registry.redhat.io/ubi9/ubi:latest@sha256:df36b9f6496df2e43672f19deca9b71828c0ee9edaa3b2b492a05c1e8eb9bd09 as builder

WORKDIR /opt/app-root/src
USER root

RUN dnf install --nodocs -y golang && \
    dnf clean all && \
    rm -rf /var/cache/yum

COPY .git .git
COPY opentelemetry-operator opentelemetry-operator
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY opentelemetry-operator/LICENSE /licenses/
WORKDIR /opt/app-root/src/opentelemetry-operator

RUN  CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime go build -C ./cmd/otel-allocator -mod=mod -tags strictfipsruntime -o ./opentelemetry-target-allocator -trimpath -ldflags "-s -w"

FROM registry.redhat.io/ubi9/ubi-micro:latest@sha256:b1e86b97028b8fcfb6d85f997c39e6b6b67496163ef8d80d243220a4918e8bef AS target-base

FROM registry.redhat.io/ubi9/ubi:latest@sha256:df36b9f6496df2e43672f19deca9b71828c0ee9edaa3b2b492a05c1e8eb9bd09 as install-additional-packages
COPY --from=target-base / /mnt/rootfs
RUN rpm --root /mnt/rootfs --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
RUN dnf install --installroot /mnt/rootfs --releasever 9 --setopt install_weak_deps=false --setopt reposdir=/etc/yum.repos.d --nodocs -y openssl && \
    dnf clean all && \
    rm -rf /var/cache/yum
RUN rm -rf /mnt/rootfs/var/cache/*

FROM scratch
WORKDIR /
COPY --from=install-additional-packages /mnt/rootfs/ /

ARG VERSION=0.152.1-2

RUN mkdir /licenses
COPY opentelemetry-operator/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/opentelemetry-operator/cmd/otel-allocator/opentelemetry-target-allocator /usr/bin/opentelemetry-target-allocator

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/opentelemetry-target-allocator"]

LABEL release="${VERSION}" \
      version="${VERSION}" \
      cpe="cpe:/a:redhat:openshift_distributed_tracing:3.10::el9" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/open-telemetry/opentelemetry-operator" \
      com.redhat.component="opentelemetry-target-allocator-container" \
      name="rhosdt/opentelemetry-target-allocator-rhel9" \
      summary="OpenTelemetry Target allocator" \
      description="Prometheus target allocator for the OpenTelemetry collector" \
      io.k8s.description="Target allocator for the OpenTelemetry collector." \
      io.openshift.expose-services="80:http" \
      io.openshift.tags="monitoring" \
      io.k8s.display-name="OpenTelemetry Target allocator"
