# Based on ./gatekeeper-operator/bundle.Dockerfile
FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:48fa5d8cda7fc00d270d8747c3eaa54ae196f0820d8540074a9c8c61d5e3056f as builder

USER root
WORKDIR /opt/bundle-build

# TODO use python3-ruamel-yaml-clib python3-ruamel-yaml once on RHEL9 which is easier to use
RUN microdnf update -y && rm -rf /var/cache/yum && \
    microdnf install -y python3 python3-pyyaml patch

RUN mkdir /licenses
COPY opentelemetry-operator/LICENSE /licenses/.

COPY bundle-patch .
COPY opentelemetry-operator/bundle/openshift/manifests manifests/
COPY opentelemetry-operator/bundle/openshift/metadata metadata/

RUN ls manifests -al
RUN ls metadata -al

# stage - registry.stage.redhat.io, prod - registry.redhat.io
ARG REGISTRY=registry.redhat.io

RUN ./update_bundle.sh && cat manifests/opentelemetry-operator.clusterserviceversion.yaml metadata/annotations.yaml

FROM scratch

ARG VERSION=0.152.1-2

WORKDIR /

# RUN mkdir /licenses
COPY opentelemetry-operator/LICENSE /licenses/.

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=opentelemetry-product
LABEL operators.operatorframework.io.bundle.channels.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.29.0
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

LABEL release="${VERSION}" \
      version="${VERSION}" \
      cpe="cpe:/a:redhat:openshift_distributed_tracing:3.10::el9" \
      com.redhat.openshift.versions=v4.12 \
      name="rhosdt/opentelemetry-operator-bundle" \
      distribution-scope="public" \
      description="Bundle for OpenTelemetry operator" \
      io.k8s.description="Bundle for OpenTelemetry operator" \
      com.redhat.component="opentelemetry-operator-bundle-container" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="OpenTelemetry Operator Bundle" \
      url="https://github.com/open-telemetry/opentelemetry-operator" \
      vendor="Red Hat, Inc." \
      summary="OpenTelemetry operator bundle" \
      maintainer="support@redhat.com"


# Copy files to locations specified by labels.
COPY --from=builder /opt/bundle-build/manifests /manifests/
COPY --from=builder /opt/bundle-build/metadata /metadata/
COPY opentelemetry-operator/bundle/openshift/tests/scorecard /tests/scorecard/

ARG USER_UID=1001
USER ${USER_UID}
